# Site settings
title: Kristen Brickner | Security Research
description: Building in public - AI/Cloud security research, tools, and learning journey
author: Kristen Brickner

# Build settings
theme: minima
markdown: kramdown

# Social links (NO @ symbol for twitter!)
github_username: kbrickz
x_username: kaybrickz

# Exclude from processing
exclude:
  - README.md
```
