# Site settings
title: Kristen Brickner | Security Research
description: Building in public - AI/Cloud security research, tools, and learning journey
baseurl: ""
url: "https://kbrickz.github.io"

# Author
author: Kristen Brickner

# Build settings
remote_theme: jekyll/minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Minima theme settings
minima:
  skin: dark

#Navigation
header_pages:
  - about.md

# Social links
github_username: kbrickz
x_username: kaybrickz

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
